export const actionTypes = {
    ADDNUMBER: Symbol('ADDNUMBER'),
    ADDRANDOMNUMBER: Symbol('ADDRANDOMNUMBER'),
    ASYNCADDNUMBER: Symbol('ASYNCADDNUMBER'),
    FETCHDATATAKEEVERY: Symbol('FETCHDATATAKEEVERY'),
    FETCHDATATAKELAETEST: Symbol('FETCHDATATAKELAETEST'),
    FETCHDATATAKELEADING: Symbol("FETCHDATATAKELEADING"),
    FETCHDATATHROTTLE: Symbol('FETCHDATATHROTTLE'),
}
